// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szkfhwgmkigvcxpupwgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6a2Zod2dta2lndmN4cHVwd2duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2ODAzNjgsImV4cCI6MjA2NTI1NjM2OH0.0C85WHffOFxLXu7QWSG4D4SyVuL6plmTYjWdNZtKo8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);